# Nombre del workflow
name: CI/CD Frontend

# Controla lo que se va a ejecutar (Trigger) pull, push, pull request
on:
    push:
        branches: [release, develop, feature/auth]
    pull_request:
        branches: [release, develop, feature/auth]

# Pasos a realizar
jobs:
    sistema-ventas-web:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: sistema-ventas-web
        steps:
            - uses: actions/checkout@v4 # Clonar el repositorio actual
            - uses: actions/setup-node@v4 # Usar node
              with:
                node-version: 22.16.0 # Versión de Node
            
            # Cargar cache de node_midules, para reducir el tiempo de instalación en proximas ejecuciones
            - name: Cache node modules
              id: node-cache
              uses: actions/cache@v4
              with:
                path: sistema-ventas-web/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('sistema-ventas-web/package-lock.json') }}

            # Instalar las dependencias 
            - name: Install dependencies
              # No ejecutar si se obtuvo el nide_modules de cache
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: npm install 
              working-directory: sistema-ventas-web